runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail_bounce

handlers:
- url: /sendout
  script: main.app
- url: /_ah/bounce
  script: handle_bounced_email.app
  login: admin

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
